### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by mbevila** [HSLCY/GlossBERT#2]
Hello,

are there plans to release pretrained models? The model is very expensive to train, and the research community would really benefit from having them available.

Thanks in advance.

**Comment by HSLCY** [comment]
Hello, I've received your email.

The model was lost because the server was formatted and I did't make a backup.  (sad)
But I'm training a new model with the same hyperparameters for you.

And I'm very sorry that the new model might be slightly different (but comparable) from the original one because the old GPUs have been upgraded to new ones whose type is different (from Tesla V100-PCIE to Tesla V100-SXM2).

It takes 30+ hours to train and I will write to you after it finishes.

Thanks for your waiting.
