### ISSUE TITLE
issues regarding the overall performance Table 3

### ISSUE THREAD

**Issue by lwmlyy** [HSLCY/GlossBERT#3]
We have checked the POS performance listed in Table 3 but the statistics do not add up. The overall performance is 77.6 (not 77.0) if we add all correct instances from each POS, shown in the following table, please check, THX.

  | N | V | A | R | ALL |  
-- | -- | -- | -- | -- | -- | --
  | 4300 | 1652 | 955 | 346 | 7253 |  
SE07 | 159 | 296 |   |   | 455 |  
  | 4141 | 1356 | 955 | 346 | 6798 |  
  | 79.8 | 67.1 | 79.6 | 87.4 | 77 |  
  | 3304.518 | 909.876 | 760.18 | 302.404 | 5276.978 |  
  |   |   |   |   | 0.776254 |

**Comment by HSLCY** [comment]
Thank you very much. I have checked and it proves that we have made some mistakes. Since the evaluation framework does not provide four POS datasets, we produce these four datasets by ourselves. In our original experiments, we only test on ALL and then separate the results to four POS sets and then run `Scorer.java` to calculate the metrics, in which we have made some mistakes and the number of each set is not corresponding to the gold one. So the result of ALL is correct and the results of four POS are a bit higher. The correct results are:

|N | V | A | R | ALL|
|-- | -- | -- | -- | -- |
|79.3 | 66.9 | 78.2 | 86.4 | 77.0 | 

The POS parts of the last four rows in Table 3 are all affected by this mistake, and we will update the arXiv version.

THX.

![image](https://user-images.githubusercontent.com/48792690/71781617-ccfb0d80-300b-11ea-9dcb-dce10a292799.png)
